In [1]:
import tensorflow as tf
print("tf ver = ", tf.__version__)

tf ver =  2.4.0


In [2]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]
b = [[1,1,1],
    [1,1,1],
    [1,1,1]]

In [3]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
b

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [7]:
c = [ [0] * 3 for i in range(3)]

In [8]:
c

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [9]:
a+b

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [13]:
for i in range(0,3):
    for j in range(0,3):
        c[i][j] = a[i][j] + b[i][j]
c
    

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [14]:
import numpy as np 
np.array(a) + np.array(b)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [15]:
np.array([2,3,4])

array([2, 3, 4])

In [16]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [19]:
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

In [21]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.array([[1,2,3],[4,5,6]]).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
np.array([[1,2,3],[4,5,6]]).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
np.array([[1,2,3],[4,5,6]]).T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
m = np.array([[0,1,2,3,4],
             [5,6,7,8,9],
             [10,11,12,13,14]])

In [26]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
m[1][2]

7

In [34]:
m[2][4]

14

In [91]:
m[1,1:3]

array([6, 7])

In [94]:
m[1,2]

7

In [95]:
m[1:3,2]

array([ 7, 12])

In [96]:
m[0:2,3:5]

array([[3, 4],
       [8, 9]])

In [97]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [98]:
np.save("my_array",a)

In [102]:
np.savetxt("my_array.csv",a)

In [104]:
b= np.loadtxt("my_array.csv")

In [106]:
def f(x):
    print(id(x))

In [110]:
a =1

In [112]:
id(a)

1371910336

In [114]:
a1 = 123

In [115]:
id(a1)

1371914240

In [116]:
b1 = "abc" ; id(b1)

1741859666720

In [117]:
c1 = a1

In [118]:
print("a1 =" , id(a1))
print("c1 =" , id(c1))


a1 = 1371914240
c1 = 1371914240


In [119]:
c1 = 999

In [120]:
a1

123

In [121]:
c1

999

In [122]:
print("a1 =" , id(a1))
print("c1 =" , id(c1))

a1 = 1371914240
c1 = 1743381736880


In [123]:
s= np.array([i,j]);s

array([2, 2])

In [126]:
i

2