In [1]:
import tensorflow as tf
import numpy as np

In [7]:
rank_0 = tf.constant(4)
rank_0

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [8]:
print(rank_0)

tf.Tensor(4, shape=(), dtype=int32)


In [9]:
rank_1 = tf.constant([2.0,3.0,4.0])
print(rank_1)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [14]:
rank_2 = tf.constant([[1,2],
                    [3,4],
                    [5,6]], dtype = tf.float16)
print(rank_2)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [18]:
rank_3 = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

In [19]:
print(rank_3)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [21]:
a = tf.constant([[1,2],
                [3,4]])
b = tf.constant([[1,2],
                [3,4]])


In [23]:
c = tf.constant([[4.0,5.0],
               [10.0,1.0]])

In [24]:
tf.reduce_max(c) # 큰 숫자 값 정보

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [26]:
tf.argmax(c) # 큰 숫자 위치 정보 

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0], dtype=int64)>

In [27]:
tf.nn.softmax(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>

In [29]:
rank_4 = tf.zeros([3,2,4,5])

In [30]:
rank_4.dtype

tf.float32

In [31]:
rank_4.ndim

4

In [32]:
rank_4

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
rank_4.shape

TensorShape([3, 2, 4, 5])

In [34]:
rank_4.shape[0]

3

In [35]:
rank_4.shape[-1]

5

In [36]:
tf.size(rank_4).numpy()

120

In [39]:
 tf.reshape(rank_3, [2,3,4])

InvalidArgumentError: Input to reshape is a tensor with 30 values, but the requested shape has 24 [Op:Reshape]

In [40]:
tf.reshape(rank_3, [2,3,5])

<tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

In [41]:
tf.reshape(rank_3, [6,5])

<tf.Tensor: shape=(6, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])>

In [42]:
tf.reshape(rank_3, [5,6])

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])>

In [47]:
tf.reshape(rank_3, [3,-1])

<tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])>

In [49]:
try: 
    tf.reshape(rank_3, [3,-1])
except Exception as e:
    print(f"{type(e)})

SyntaxError: EOL while scanning string literal (<ipython-input-49-e93d788a98d2>, line 4)

In [51]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

