In [1]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
X = [[1, 2, 3],
    [11, 12, 13],
    [23,33,45]]
y = [0, 1,0 ]
clf.fit(X,y)


RandomForestClassifier(random_state=0)

In [2]:
clf.predict(X)

array([0, 1, 0])

In [3]:
clf.predict([[235,23,456]])

array([0])

In [4]:
import numpy as np
rs = np.random.RandomState(50) # randomstate에 값이 없으면 계속 결과값이 바뀜
x = 10 * rs.rand(7)
y = 2 * x - 1 * rs.rand(7)
x.shape, y.shape

((7,), (7,))

In [5]:
X = x.reshape(-1,1)
X.shape

(7, 1)

In [6]:
X

array([[4.94601646],
       [2.28083104],
       [2.55473924],
       [3.9632991 ],
       [3.77315098],
       [9.9657423 ],
       [4.081972  ]])