In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [19]:
type(iris)

sklearn.utils.Bunch

In [23]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [21]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [22]:
X = iris.data[:,2:]

In [4]:
iris.target[:5]

array([0, 0, 0, 0, 0])

In [24]:
import numpy as np
np.unique(iris.target, return_counts=True)
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [25]:
y = iris.target

In [26]:
iris.data[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [8]:
# iris 데이터셋 준비
from sklearn.datasets import load_iris
iris = load_iris()
# 특징행렬(데이터)과 대상 벡터(레이블) 만들기
X = iris.data[:,2:]
y = iris.target


In [9]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=2)

tree.fit(X,y)

DecisionTreeClassifier(max_depth=2)

In [10]:
tree.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 2,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [11]:
from sklearn.tree import export_graphviz

dot_data = export_graphviz(tree, 
                out_file=None,
                feature_names=iris.feature_names[2:],
                class_names=iris.target_names,
                rounded=True,
                filled=True,
                impurity=True)

import pydotplus
graph = pydotplus.graph_from_dot_data(dot_data)

In [12]:
#import os
#os.environ["PATH"] += os.pathsep +'C:/Program Files/Graphviz 2.44.1/bin'

graph.write_png("iris.png")

from Ipython.core.display import image
imgae("iris.png")

InvocationException: Program terminated with status: 1. stderr follows: Format: "png" not recognized. Use one of:


In [13]:
from sklearn.tree import export_graphviz

dot_data = export_graphviz(tree, out_file=None, 
                           feature_names= iris.feature_names[2:], 
                           class_names=iris.target_names, rounded=True, 
                           filled=True, impurity=True)

import pydotplus

graph = pydotplus.graph_from_dot_data(dot_data)

graph.write_png("iris.png")

from IPython.core.display import Image
Image("iris.png")


InvocationException: Program terminated with status: 1. stderr follows: Format: "png" not recognized. Use one of:


In [42]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.keys()

iris.data[:5]
iris.feature_names

X= iris.data[:, 2:]

iris.target[:5]

import numpy as np

np.unique(iris.target, return_counts=True)
iris.target_names
y= iris.target

from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=2)
tree.fit(X,y)

from sklearn.metrics import accuracy_score
print("예측 정확도 : {0:.4f}",format(accuracy_score(y_test,pred)))


NameError: name 'y_test' is not defined

In [39]:
iris.data[2:2] 

array([], shape=(0, 4), dtype=float64)

In [29]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [27]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [15]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.keys()
iris.data[:5]
iris.feature_names

X= iris.data[:, 2:]

iris.target[:5]

import numpy as np

np.unique(iris.target, return_counts=True)
iris.target_names
y= iris.target

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(max_depth=3)
tree.fit(X,y)

from sklearn.tree import export_graphviz

export_graphviz(tree, out_file = "iris.dot",
                feature_names=iris.feature_names[2:],
                class_names=iris.target_names , 
                rounded =True ,
                filled=True, 
                impurity=True)

import pydot

graph = pydot.graph_from_dot_file("iris.dot")[0]
iris_png =graph.create_png()
graph.write_png("iris.png")
from IPython.core.display import Image
Image(iris_png)


FileNotFoundError: [WinError 2] "dot" not found in path.

In [16]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.keys()

iris.data[:5]
iris.feature_names

X= iris.data[:, 2:]

iris.target[:5]

import numpy as np

np.unique(iris.target, return_counts=True)
iris.target_names
y= iris.target

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(max_depth=3)
tree.fit(X,y)

from sklearn.tree import export_graphviz

export_graphviz(tree, out_file = "iris.dot",
                feature_names=iris.feature_names[2:],
                class_names=iris.target_names , 
                rounded =True ,
                filled=True, 
                impurity=True)

import pydot

graph = pydot.graph_from_dot_file("iris.dot")[0]
iris_png =graph.create_png()
graph.write_png("iris.png")
from IPython.core.display import Image
Image(iris_png)


FileNotFoundError: [WinError 2] "dot" not found in path.