In [1]:
import tensorflow as tf
print("tf ver =", tf.__version__)

tf ver = 2.4.0


In [2]:
x = tf.constant(1)
y = tf.constant(2)
z = tf.constant(3)
a = x * y + z

sess = tf.Session()
b = sess.run(a)
print(b)

AttributeError: module 'tensorflow' has no attribute 'Session'

In [3]:
x = tf.constant(1)
y = tf.constant(2)
z = tf.constant(3)
a = x * y + z

print(a)

tf.Tensor(5, shape=(), dtype=int32)


In [8]:
# TF 1.0 버전을 쓸수 있는 방법 

import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior()
x = tf.constant(1)
y = tf.constant(2)
z = tf.constant(3)
a = x * y + z

sess = tf.compat.v1.Session()
b = sess.run(a)
print(b)

5


In [4]:
a = tf.constant([[1,2],[3,4],[5,6]])

print(a.dtype)
print(a.shape)

<dtype: 'int32'>
(3, 2)


In [5]:
a = tf.constant([[1,2],[3,4],[5,6],
                 [7,8],[9,10],[11,2]])
print(a)

tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11  2]], shape=(6, 2), dtype=int32)


In [6]:
a = tf.constant([[1.,2],[3,4],[5,6], # 소수점이 있으면 소수로 바뀐다.
                 [7,8],[9,10],[11,2]])
print(a)

tf.Tensor(
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]
 [11.  2.]], shape=(6, 2), dtype=float32)


In [7]:
b = tf.reshape(a, [-1,6]) ; b

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.,  2.]], dtype=float32)>

In [8]:
tf.transpose(b) # 전치행렬

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  7.],
       [ 2.,  8.],
       [ 3.,  9.],
       [ 4., 10.],
       [ 5., 11.],
       [ 6.,  2.]], dtype=float32)>

In [10]:
b

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11.,  2.]], dtype=float32)>

In [16]:
a_data = [1,2,3,4,5]
b_data = [-1,-1,-1,-1,-1]

a = tf.constant(a_data)
b = tf.constant(b_data)

c= a* b
print(c)

tf.Tensor([-1 -2 -3 -4 -5], shape=(5,), dtype=int32)


In [17]:
d = c.numpy()

In [21]:
df=pd.DataFrame(d)

In [26]:
a_data = [1,2,3,4,5]
b_data = [1,4,6,4,9]

a = tf.constant(a_data)
b = tf.constant(b_data)

tf.equal(a,b)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True, False, False,  True, False])>