In [4]:
import tensorflow as tf
import cProfile

In [8]:
tf.executing_eagerly() # tf2.0은 True 기본값

x = [[2.]]
m = tf.matmul(x,x)
print("hello,{}".format(m))

hello,[[4.]]


In [10]:
a  = tf.constant([[1, 2],
                 [3, 4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [11]:
tf.add(a,1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [12]:
c = tf.constant([[1,1],
                [1,1]])
tf.add(a,c)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [13]:
b = tf.add(a,1)

In [14]:
print(a*b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [16]:
#numpy 값 사용
import numpy as np
c = np.multiply(a,b)
print(c)

[[ 2  6]
 [12 20]]


동적인 제어 흐름

In [19]:
def fizzbuzz(max_num):
    counter = tf.constant(0)
    max_num = tf.convert_to_tensor(max_num)
    for num in range(1, max_num.numpy()+1):
        num = tf.constant(num)
        print("~~~ -->", num)
        if int(num % 3) == 0 and int(num % 5 ) == 0:
            print('Fizzbuzz')
        elif int(num % 3 ) == 0 :
            print('Fizz')
        elif int(num % 5) == 0 :
            print('Buzz')
        else :
            print(num.numpy())
        counter += 1

In [20]:
fizzbuzz(15)

~~~ --> tf.Tensor(1, shape=(), dtype=int32)
1
~~~ --> tf.Tensor(2, shape=(), dtype=int32)
2
~~~ --> tf.Tensor(3, shape=(), dtype=int32)
Fizz
~~~ --> tf.Tensor(4, shape=(), dtype=int32)
4
~~~ --> tf.Tensor(5, shape=(), dtype=int32)
Buzz
~~~ --> tf.Tensor(6, shape=(), dtype=int32)
Fizz
~~~ --> tf.Tensor(7, shape=(), dtype=int32)
7
~~~ --> tf.Tensor(8, shape=(), dtype=int32)
8
~~~ --> tf.Tensor(9, shape=(), dtype=int32)
Fizz
~~~ --> tf.Tensor(10, shape=(), dtype=int32)
Buzz
~~~ --> tf.Tensor(11, shape=(), dtype=int32)
11
~~~ --> tf.Tensor(12, shape=(), dtype=int32)
Fizz
~~~ --> tf.Tensor(13, shape=(), dtype=int32)
13
~~~ --> tf.Tensor(14, shape=(), dtype=int32)
14
~~~ --> tf.Tensor(15, shape=(), dtype=int32)
Fizzbuzz


In [24]:
w = tf.Variable([[1.0]])
with tf.GradientTape() as tape:

grad = tape.gradient(loss, w)
print(grad)  # => tf.Tensor([[ 2.]], shape=(1, 1), dtype=float32)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


In [26]:
w = tf.Variable([[1.0]])
loss = w * w


In [27]:
w

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[1.]], dtype=float32)>

In [29]:
(mnist_images, mnist_labels), _ = tf.keras.datasets.mnist.load_data()

datasets = tf.data.Dataset.from_tensor_slices(
    (tf.cast(mnist_images[...,tf.newaxis]/255, tf.float32),
    tf.cast(mnist_labels,tf.int64)))
datasets=datasets.shuffle(1000).batch(32)

In [31]:
mnist_images.shape

(60000, 28, 28)

In [41]:
a = mnist_images[...,tf.newaxis] #...앞에는 알아서 해주세요..

In [34]:
a.shape 

(60000, 28, 28, 1)

In [36]:
mnist_images[tf.newaxis,:,:].shape

(1, 60000, 28, 28)

In [38]:
mnist_images[:,tf.newaxis,:].shape

(60000, 1, 28, 28)

In [40]:
mnist_images[:,tf.newaxis,:,:].shape

(60000, 1, 28, 28)

In [45]:
mnist_model = tf.keras.Sequential([
  tf.keras.layers.Conv2D(16,[3,3], activation='relu',
                         input_shape=(None, None, 1)),
  tf.keras.layers.Conv2D(16,[3,3], activation='relu'),
  tf.keras.layers.GlobalAveragePooling2D(),
  tf.keras.layers.Dense(4)
])

# 객체 기반의 저장 

In [46]:
x = tf.Variable(10.)
checkpoint = tf.train.Checkpoint(x=x)
checkpoint

In [47]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>

In [48]:
x.assign(2.)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [49]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [51]:
checkpoint_path ="./ckpt/"
checkpoint.save(checkpoint_path)

'./ckpt/-1'

In [52]:
x.assign(11.)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=11.0>

In [53]:
checkpoint.restore(tf.train.latest_checkpoint(checkpoint_path))

In [54]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [63]:
m = tf.keras.metrics.Mean("loss")
m(0)


<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [64]:
m(5)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [65]:
m([8,15])

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>